# if given, will override the device setting in gym.
env:
  objectId: 19179
  numEnvs: 200
  envSpacing: 2.5
  episodeLength: 500
  enableDebugVis: False
  initPose: 4
  video: False

  startPositionNoise: 0.0
  startRotationNoise: 0.0

  aggregateMode: 0
  pushDist: 0.16

  actionScale: 7.5
  dofVelocityScale: 0.1
  boxSize: 0.16

  rewardScale: 4.0
  actionPenaltyScale: 0.01

sim:
  # Note: using 2 substeps sometimes needs required for better grasping behavior, but 1 is faster
  dt: 0.01
  substeps: 1
  physx:
    num_threads: 4
    solver_type: 1  # 0: pgs, 1: tgs
    num_position_iterations: 8
    num_velocity_iterations: 0
    contact_offset: 0.001
    rest_offset: 0.0
    bounce_threshold_velocity: 0.5
    max_depenetration_velocity: 1000.0
    default_buffer_size_multiplier: 5.0
    always_use_articulations: False
    friction_offset_threshold: 0.001
    friction_correlation_distance: 0.0005

  flex:
    num_outer_iterations: 4
    num_inner_iterations: 15
    warm_start: 0.8
    relaxation: 0.75

task:
  randomize: False
